global:
  imagePullPolicy: Always
  ###vault:
  ###  host: ip
  ###  name: vault
  ###  vaultToken: someToken


frontend:
### В чарте frontend отсутствуют некоторые важные файлы. Поймите какие и опишите их.
  replicas: 1
  revisionHistoryLimit: 15
  strategy:
    type: Recreate
  service:
    port: 80
  ingress:
    enabled: true
    host: Vulkii.2sem.students-projects.ru
    tlsSecret: 2sem-students-projects-wildcard-secret
    path: /
    pathType: Prefix
  containerPort: 80
  image: YOUR_DOCKERHUB/sausage-frontend:latest
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "1"
  nginxConf: nginx.conf

backend:
  annotations:
    path: /actuator/prometheus
    port: "8080"
    scrape: "true"
  env:
    postgresUri: jdbc:postgresql://postgresql:5432/sausage-store
    postgresUser: store
    postgresPassword: storepassword
    reportPath: /logs/reports
    logPath: /logs
  service:
    port: 8080
  revisionHistoryLimit: 15
  replicas: 1
  strategy:
  ### Опишите стратегию RollingUpdate для бэкенда
  image: YOUR_DOCKERHUB/sausage-backend:latest
  imagePullPolicy: Always
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "1"
  containerPort: 8080
  livenessProbe:
  ### Опишите LivenessProbe для бэкенда
  vpa:
  ### Опишите VPA для бэкенда

backend-report:
  image: YOUR_DOCKERHUB/sausage-backend-report:latest"

  global:
    imagePullPolicy: IfNotPresent

  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate

  containerPort: 8080

  env:
    port: "8080"                             # PORT
    db: "mongodb://mongodb:27017/reports"    # DB

  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"

  livenessProbe:
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 10
    periodSeconds: 20

  readinessProbe:
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10

  # HPA
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    cpuUtilizationPercentage: 60


infra:
  postgresql:
  mongodb:
    env:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    containerPort: 27017
  postgresql:
    env:
      POSTGRESQL_INITDB_ROOT_USERNAME: store
      POSTGRESQL_INITDB_ROOT_PASSWORD: storepassword
      POSTGRESQL_INITDB_ROOT_DB: sausage-store
    containerPort: 5432

