global:
  imagePullPolicy: Always


frontend:
  replicas: 1
  revisionHistoryLimit: 15
  strategy:
    type: Recreate
  service:
    port: 80
  ingress:
    enabled: true
    host: Vulkii.2sem.students-projects.ru
    tlsSecret: 2sem-students-projects-wildcard-secret
    path: /
    pathType: Prefix
  containerPort: 80
  image: p1lan/sausage-frontend:latest
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "1"
  nginxConf: nginx.conf

backend:
  annotations:
    path: /actuator/prometheus
    port: "8080"
    scrape: "true"
  env:
    postgresUri: jdbc:postgresql://postgresql:5432/sausage-store
    postgresUser: store
    postgresPassword: storepassword
    reportPath: /logs/reports
    logPath: /logs
  service:
    port: 8080
  revisionHistoryLimit: 15
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  image: p1lan/sausage-backend:latest
  imagePullPolicy: Always
  resources:
    requests:
      memory: "256Mi"
      cpu: "150m"
    limits:
      memory: "512Mi"
      cpu: "300m"
  containerPort: 8080
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 20
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 3
  vpa:
    enabled: true
    updatePolicy:
      updateMode: "Off"
    resourcePolicy:
      containerPolicies:
        - containerName: "*"
          minAllowed:
            cpu: "150m"
            memory: "256Mi"
          maxAllowed:
            cpu: "1"
            memory: "512Mi"

backend-report:
  image: p1lan/sausage-backend-report:latest

  global:
    imagePullPolicy: IfNotPresent

  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate

  containerPort: 8080

  env:
    port: "8080"
    db: "mongodb://mongodb:27017/reports"

  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"

  livenessProbe:
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 15
    periodSeconds: 20

  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    cpuUtilizationPercentage: 60


infra:
  postgresql:
  mongodb:
    env:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    containerPort: 27017
  postgresql:
    env:
      POSTGRESQL_INITDB_ROOT_USERNAME: store
      POSTGRESQL_INITDB_ROOT_PASSWORD: storepassword
      POSTGRESQL_INITDB_ROOT_DB: sausage-store
    containerPort: 5432

