---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  annotations:
    helm.sh/hook-weight: "-5"
spec:
  serviceName: postgresql
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:15
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          envFrom:
            - configMapRef:
                name: postgresql-conf
          ports:
            - containerPort: {{ .Values.postgresql.containerPort }}
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              cpu: "100m"
              memory: "256Mi"
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgresql-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  ports:
    - port: {{ .Values.postgresql.containerPort }}
      targetPort: {{ .Values.postgresql.containerPort }}
  selector:
    app: postgresql
  clusterIP: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-conf
data:
  POSTGRES_USER: {{ .Values.postgresql.env.POSTGRESQL_INITDB_ROOT_USERNAME }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.env.POSTGRESQL_INITDB_ROOT_PASSWORD }}
  POSTGRES_DB: {{ .Values.postgresql.env.POSTGRESQL_INITDB_ROOT_DB }}