apiVersion: v1
kind: Service
metadata:
  name: sausage-store-frontend-service
  labels:
    app: sausage-store-frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.containerPort }}
  selector:
    app: sausage-store-frontend
